name: ci

on:
  push:
  pull_request:

jobs:
  build-mre:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build progs.dat
        shell: pwsh
        run: .\ci\build_mre.ps1
      - name: Upload progs.dat
        uses: actions/upload-artifact@v4
        with:
          name: mre-progs.dat
          path: ci/mre/progs.dat
